-- =====================================================================
-- MOTIVA - Sprint 4
-- Dados de teste (opcional)
--
-- Rode SOMENTE se o seu schema estiver vazio, ou seja, se voce criou as
-- tabelas com 01_create_tables_sprint4.sql. Se voce migrou o banco da
-- Sprint 3 com o script 02, os dados da Sprint 3 ja estao la e este
-- arquivo NAO deve ser executado (ele duplicaria os registros).
--
-- Diferenca para o insert_data.sql da Sprint 3: aqui o ID e informado
-- explicitamente a partir da sequence (SEQ_X.NEXTVAL), exatamente como o
-- Hibernate fara em tempo de execucao.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1) EQUIPE_MANUTENCAO
-- ---------------------------------------------------------------------
INSERT INTO EQUIPE_MANUTENCAO (ID, NOME, QUANTIDADE_INTEGRANTES)
VALUES (SEQ_EQUIPE_MANUTENCAO.NEXTVAL, 'Equipe Alpha', 6);

INSERT INTO EQUIPE_MANUTENCAO (ID, NOME, QUANTIDADE_INTEGRANTES)
VALUES (SEQ_EQUIPE_MANUTENCAO.NEXTVAL, 'Equipe Beta', 4);

INSERT INTO EQUIPE_MANUTENCAO (ID, NOME, QUANTIDADE_INTEGRANTES)
VALUES (SEQ_EQUIPE_MANUTENCAO.NEXTVAL, 'Equipe Gama', 5);

-- ---------------------------------------------------------------------
-- 2) TRECHO_RODOVIA
--    TIPO_TRECHO: UMIDO | SECO | UMIDO_MONITORADO
-- ---------------------------------------------------------------------
INSERT INTO TRECHO_RODOVIA
    (ID, QUILOMETRO_INICIAL, QUILOMETRO_FINAL, NIVEL_VEGETACAO_CM, TIPO_TRECHO,
     INDICE_PLUVIOMETRICO, EM_ESTACAO_SECA, ID_SENSOR, ID_EQUIPE_RESPONSAVEL)
VALUES (SEQ_TRECHO_RODOVIA.NEXTVAL, 0, 10, 72.5, 'UMIDO_MONITORADO',
        1.20, NULL, 'SENSOR-BR116-KM05', NULL);

INSERT INTO TRECHO_RODOVIA
    (ID, QUILOMETRO_INICIAL, QUILOMETRO_FINAL, NIVEL_VEGETACAO_CM, TIPO_TRECHO,
     INDICE_PLUVIOMETRICO, EM_ESTACAO_SECA, ID_SENSOR, ID_EQUIPE_RESPONSAVEL)
VALUES (SEQ_TRECHO_RODOVIA.NEXTVAL, 10, 20, 46.0, 'UMIDO',
        1.80, NULL, NULL, (SELECT ID FROM EQUIPE_MANUTENCAO WHERE NOME = 'Equipe Alpha'));

INSERT INTO TRECHO_RODOVIA
    (ID, QUILOMETRO_INICIAL, QUILOMETRO_FINAL, NIVEL_VEGETACAO_CM, TIPO_TRECHO,
     INDICE_PLUVIOMETRICO, EM_ESTACAO_SECA, ID_SENSOR, ID_EQUIPE_RESPONSAVEL)
VALUES (SEQ_TRECHO_RODOVIA.NEXTVAL, 20, 30, 41.0, 'SECO',
        NULL, 'N', NULL, NULL);

INSERT INTO TRECHO_RODOVIA
    (ID, QUILOMETRO_INICIAL, QUILOMETRO_FINAL, NIVEL_VEGETACAO_CM, TIPO_TRECHO,
     INDICE_PLUVIOMETRICO, EM_ESTACAO_SECA, ID_SENSOR, ID_EQUIPE_RESPONSAVEL)
VALUES (SEQ_TRECHO_RODOVIA.NEXTVAL, 30, 40, 88.0, 'SECO',
        NULL, 'S', NULL, (SELECT ID FROM EQUIPE_MANUTENCAO WHERE NOME = 'Equipe Beta'));

INSERT INTO TRECHO_RODOVIA
    (ID, QUILOMETRO_INICIAL, QUILOMETRO_FINAL, NIVEL_VEGETACAO_CM, TIPO_TRECHO,
     INDICE_PLUVIOMETRICO, EM_ESTACAO_SECA, ID_SENSOR, ID_EQUIPE_RESPONSAVEL)
VALUES (SEQ_TRECHO_RODOVIA.NEXTVAL, 40, 50, 18.0, 'UMIDO',
        1.00, NULL, NULL, NULL);

-- ---------------------------------------------------------------------
-- 3) INTERVENCAO_OPERACIONAL
--    TIPO_INTERVENCAO: ROCADA_MECANIZADA | PULVERIZACAO
-- ---------------------------------------------------------------------
INSERT INTO INTERVENCAO_OPERACIONAL
    (ID, ID_TRECHO_ALVO, ID_EQUIPE_RESPONSAVEL, TIPO_INTERVENCAO, TIPO_PRODUTO)
VALUES (SEQ_INTERVENCAO_OPERACIONAL.NEXTVAL,
        (SELECT ID FROM TRECHO_RODOVIA WHERE QUILOMETRO_INICIAL = 30 AND QUILOMETRO_FINAL = 40),
        (SELECT ID FROM EQUIPE_MANUTENCAO WHERE NOME = 'Equipe Beta'),
        'ROCADA_MECANIZADA', NULL);

INSERT INTO INTERVENCAO_OPERACIONAL
    (ID, ID_TRECHO_ALVO, ID_EQUIPE_RESPONSAVEL, TIPO_INTERVENCAO, TIPO_PRODUTO)
VALUES (SEQ_INTERVENCAO_OPERACIONAL.NEXTVAL,
        (SELECT ID FROM TRECHO_RODOVIA WHERE QUILOMETRO_INICIAL = 10 AND QUILOMETRO_FINAL = 20),
        (SELECT ID FROM EQUIPE_MANUTENCAO WHERE NOME = 'Equipe Alpha'),
        'PULVERIZACAO', 'HERBICIDA_SELETIVO');

COMMIT;
