-- =====================================================================
-- MOTIVA - Sistema de Monitoramento e Priorização de Roçada
-- Script de dados de teste (Sprint 3)
-- Rode DEPOIS de create_tables.sql, uma única vez.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1) EQUIPE_MANUTENCAO
-- ---------------------------------------------------------------------
INSERT INTO EQUIPE_MANUTENCAO (NOME, QUANTIDADE_INTEGRANTES) VALUES ('Equipe Alpha', 6);
INSERT INTO EQUIPE_MANUTENCAO (NOME, QUANTIDADE_INTEGRANTES) VALUES ('Equipe Beta', 4);
INSERT INTO EQUIPE_MANUTENCAO (NOME, QUANTIDADE_INTEGRANTES) VALUES ('Equipe Gama', 5);

-- ---------------------------------------------------------------------
-- 2) TRECHO_RODOVIA
--    TIPO_TRECHO: UMIDO | SECO | UMIDO_MONITORADO
-- ---------------------------------------------------------------------
INSERT INTO TRECHO_RODOVIA
(QUILOMETRO_INICIAL, QUILOMETRO_FINAL, NIVEL_VEGETACAO_CM, TIPO_TRECHO, INDICE_PLUVIOMETRICO, EM_ESTACAO_SECA, ID_SENSOR, ID_EQUIPE_RESPONSAVEL)
VALUES (0, 10, 72.5, 'UMIDO_MONITORADO', 1.20, NULL, 'SENSOR-BR116-KM05', NULL);

INSERT INTO TRECHO_RODOVIA
(QUILOMETRO_INICIAL, QUILOMETRO_FINAL, NIVEL_VEGETACAO_CM, TIPO_TRECHO, INDICE_PLUVIOMETRICO, EM_ESTACAO_SECA, ID_SENSOR, ID_EQUIPE_RESPONSAVEL)
VALUES (10, 20, 46.0, 'UMIDO', 1.80, NULL, NULL, (SELECT ID FROM EQUIPE_MANUTENCAO WHERE NOME = 'Equipe Alpha'));

INSERT INTO TRECHO_RODOVIA
(QUILOMETRO_INICIAL, QUILOMETRO_FINAL, NIVEL_VEGETACAO_CM, TIPO_TRECHO, INDICE_PLUVIOMETRICO, EM_ESTACAO_SECA, ID_SENSOR, ID_EQUIPE_RESPONSAVEL)
VALUES (20, 30, 41.0, 'SECO', NULL, 'N', NULL, NULL);

INSERT INTO TRECHO_RODOVIA
(QUILOMETRO_INICIAL, QUILOMETRO_FINAL, NIVEL_VEGETACAO_CM, TIPO_TRECHO, INDICE_PLUVIOMETRICO, EM_ESTACAO_SECA, ID_SENSOR, ID_EQUIPE_RESPONSAVEL)
VALUES (30, 40, 88.0, 'SECO', NULL, 'S', NULL, (SELECT ID FROM EQUIPE_MANUTENCAO WHERE NOME = 'Equipe Beta'));

INSERT INTO TRECHO_RODOVIA
(QUILOMETRO_INICIAL, QUILOMETRO_FINAL, NIVEL_VEGETACAO_CM, TIPO_TRECHO, INDICE_PLUVIOMETRICO, EM_ESTACAO_SECA, ID_SENSOR, ID_EQUIPE_RESPONSAVEL)
VALUES (40, 50, 18.0, 'UMIDO', 1.00, NULL, NULL, NULL);

-- ---------------------------------------------------------------------
-- 3) INTERVENCAO_OPERACIONAL
--    TIPO_INTERVENCAO: ROCADA_MECANIZADA | PULVERIZACAO
-- ---------------------------------------------------------------------
INSERT INTO INTERVENCAO_OPERACIONAL (ID_TRECHO_ALVO, ID_EQUIPE_RESPONSAVEL, TIPO_INTERVENCAO, TIPO_PRODUTO)
VALUES (
           (SELECT ID FROM TRECHO_RODOVIA WHERE QUILOMETRO_INICIAL = 30 AND QUILOMETRO_FINAL = 40),
           (SELECT ID FROM EQUIPE_MANUTENCAO WHERE NOME = 'Equipe Beta'),
           'ROCADA_MECANIZADA', NULL
       );

INSERT INTO INTERVENCAO_OPERACIONAL (ID_TRECHO_ALVO, ID_EQUIPE_RESPONSAVEL, TIPO_INTERVENCAO, TIPO_PRODUTO)
VALUES (
           (SELECT ID FROM TRECHO_RODOVIA WHERE QUILOMETRO_INICIAL = 10 AND QUILOMETRO_FINAL = 20),
           (SELECT ID FROM EQUIPE_MANUTENCAO WHERE NOME = 'Equipe Alpha'),
           'PULVERIZACAO', 'HERBICIDA_SELETIVO'
       );

-- ---------------------------------------------------------------------
-- 4) RELATORIO_PRIORIDADE
--    Snapshot de exemplo, equivalente a uma execução manual do service.GeradorRelatorio
-- ---------------------------------------------------------------------
INSERT INTO RELATORIO_PRIORIDADE (QT_URGENTE, QT_CRITICO, QT_ATENCAO, QT_NORMAL, RESUMO)
VALUES (1, 1, 2, 1, '5 trecho(s) analisado(s): 1 urgente(s), 1 critico(s), 2 em atencao, 1 normal(is).');

COMMIT;